name: generate animation

on:
  # Ejecutar automáticamente cada 24 horas
  schedule:
    - cron: "*/1 * * * *"
  
  # Permite ejecutar el workflow manualmente
  workflow_dispatch:
  
  # Se activa en cada push a la rama main
  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Genera la animación tipo "snake" a partir del gráfico de contribuciones del usuario
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Publica los archivos generados en la rama "output"
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
